
[[redirects]]
  from = "/vacancies/phd-phd-breas-prostate-grading/"
  to = "/vacancies/phd-phd-breast-prostate-grading/"
  status = 301

[[redirects]]
  from = "/vacancies/phd-phd-breas-prostate-grading/"
  to = "/vacancies/phd-phd-breast-prostate-grading/"
  status = 301
  
[[redirects]]
  from = "/news/launch-patholyt/"
  to = "/news/launch-aiosyn/"
  status = 301

[[redirects]]
  from = "/highlights/"
  to = "/news/"
  status = 301

[[redirects]]
  from = "/*"
  to = "https://www.computationalpathologygroup.eu/:splat"
  status = 302
  force = true
